# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93fe5646311b87e3af19ad05ccf127bfefcc19200cfa4a14bc8f2d1c61368230ee9ddbee11eb3e625b11a704b5d6e30572b0ef92a96cd2ed263258334104f0bb

test:
  secret_key_base: 81147c95d8dc8e51d29dfb9ccf77afd7154b9485dbc4de3b63e2d9536db3f6ab1d98bcaa4ebfaad589df579e93a8d93b5c5112ccb497f89078f69d4177def0c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
